### ISSUE TITLE
Confusing two question about carrying context

### ISSUE THREAD

**Issue by lisamburns** [pivotal-cf/areas-of-contribution#59]
I find myself struggling to explain the difference between these two behaviors. In both cases the story is well-defined. 

1. Is comfortable with carrying context on well-defined stories
1. Can onboard pairs into well-defined stories

When you carry-context, you naturally need to ramp your pair onto it.
Can someone clarify what the difference in behaviors this is meant to capture?

**Comment by rainmaker** [comment]
@lisamcho I'm having trouble finding the second item, which skill area was it in? I wonder if it was already removed for redundancy. In the future, we hope to have support for counting the same skill toward multiple skill areas, to reduce the feeling of redundancy when wording is slightly different.

I agree that 1. implicitly includes 2., but I think it also implies that the person is making technical decisions over a period of time, reporting back to the team, and carrying context in other ways. So I'd guess that 2. is a subset of 1. and is meant to come first.

For now, I'm going to close this because I can't find the second item, but thanks for the issue to clarify the difference.
