### ISSUE TITLE
Technical Execution: "Is comfortable with rotating pairs frequently"

### ISSUE THREAD

**Issue by aramprice** [pivotal-cf/areas-of-contribution#7]
I feel that we should revisit this question. There is mounting evidence that rotating for rotation's sake may not be helpful.

Perhaps this is better worded as: "Is comfortable pairing with everyone on the team" or replaced entirely. I'm not certain what the original driver for this question is.

**Comment by utako** [comment]
i'm also curious about the original driver. if there are problematic or difficult pairs on the team, I'm not sure if this lends itself to unbiased feedback.

**Comment by thereses** [comment]
@zvance want to comment on your experience on the RMQ team?

**Comment by zvance** [comment]
I assume this is the daily rotations on teams and not rotations within teams.

I agree that we should reframe this to be around the behavior we want to see rather than the action we think gets there.  I believe people rotate on stories primarily for context on stories (both the new work and the existing codebase/test coverage) and to have fresh ideas on how to tackle a story. On RMQ, we have had pairs stick when the benefits of those don't outweigh the cost of switching (e.g., really long running stories on which most people have visibility). I'd like to see this reframed as:

"Comfortable diving into started work without full context"
"Can bring new ideas, perspectives and challenges to technical execution of work"
"Compassionate guide and good communicator on explaining in-flight work to someone without context"

**Comment by rosenhouse** [comment]
@aramprice, thanks for opening this.

We're starting to re-invest in this repo, and the first priority is to enable a pull-request-based contribution model for changing the content.  We've put a bit more detail about our plans [this roadmap](https://github.com/pivotal-cf/areas-of-contribution/blob/master/CONTRIBUTING.md#roadmap).

We don't have anything actionable yet. But after we've made progress on the roadmap, we intend to respond again here with pointers to a contribution workflow that you or others could follow to address this issue.

Thanks for your patience!
