### ISSUE TITLE
Change layout of tables to not hide higher p-levels

### ISSUE THREAD

**Issue by sunjayBhatia** [pivotal-cf/areas-of-contribution#9]
Github's default width for rendering markdown is not very wide and some of the tables with a lot of content end up getting cut off on the right (e.g. https://github.com/pivotal-cf/areas-of-contribution/blob/296124f22aaba971aa1f51fef82ff386a166a232/cf-domain-expertise.md).

Could we flip the orientation of the tables or make some other formatting changes so as not to hide higher p-level content?

**Comment by utako** [comment]
we'd accept PRs with any suggestions, @sunjayBhatia!

**Comment by rosenhouse** [comment]
@sunjayBhatia Thanks for raising this issue.

As @utako said, we'd welcome a PR here now.  In addition, I'd share that we're hoping to roll out some tooling related to the markdown files here.  Once that is in place, it could enable you (or others) to address this rendering issue by changing a single template file, rather than each markdown file individually.

We've put a bit more detail about our high-level plans [this roadmap](https://github.com/pivotal-cf/areas-of-contribution/blob/master/CONTRIBUTING.md#roadmap).  We'll respond again here once we've made progress on the tooling work.
